/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJNI */

#ifndef _Included_TestJNI
#define _Included_TestJNI

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     TestJNI
 * Method:    testJniAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_TestJNI_testJniAdd(JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif

#endif // _Included_TestJNI
